version: "3.9"

services:

  postgres:
    image: pgvector/pgvector:pg16

    container_name: insurance-rag-postgres

    environment:
      POSTGRES_USER: sso_user
      POSTGRES_PASSWORD: sso_pass
      POSTGRES_DB: sso_db

    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: